import React from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Linking,
} from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '@/constants/Colors';

export default function TermsOfServiceScreen() {
  const router = useRouter();

  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={22} color={Colors.foreground} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Terms and Conditions</Text>
        <View style={styles.headerSpacer} />
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={styles.content}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.lastUpdated}>Last Updated: March 2026</Text>

        <Text style={styles.body}>
          These Terms and Conditions govern your use of the Juno website and services.
        </Text>
        <Text style={styles.body}>By using Juno, you agree to these terms.</Text>

        <Text style={styles.sectionTitle}>1. Description of Service</Text>
        <Text style={styles.body}>
          Juno provides an AI-powered tool that helps users summarize and better understand medical
          conversations, recordings, and documents.
        </Text>
        <Text style={styles.body}>The service may:</Text>
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}>• Generate summaries of uploaded recordings, notes, or documents</Text>
          <Text style={styles.bulletItem}>• Explain complex medical information in simpler language</Text>
          <Text style={styles.bulletItem}>• Suggest potential follow-up questions for healthcare providers</Text>
        </View>
        <Text style={styles.body}>Juno is designed to support medical understanding and literacy.</Text>

        <Text style={styles.sectionTitle}>2. Not Medical Advice</Text>
        <Text style={styles.body}>
          Juno <Text style={styles.bold}>does not provide medical advice</Text>.
        </Text>
        <Text style={styles.body}>
          The information generated by Juno is for{' '}
          <Text style={styles.bold}>informational and educational purposes only</Text> and should{' '}
          <Text style={styles.bold}>
            not be used as a substitute for professional medical advice, diagnosis, or treatment
          </Text>
          .
        </Text>
        <Text style={styles.body}>
          Always seek guidance from qualified healthcare professionals regarding medical decisions.
        </Text>

        <Text style={styles.sectionTitle}>3. User Responsibility</Text>
        <Text style={styles.body}>
          You are responsible for the information you upload or submit to the service.
        </Text>
        <Text style={styles.body}>You should only upload content that:</Text>
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}>• You have the legal right to use or share</Text>
          <Text style={styles.bulletItem}>• Does not violate applicable laws or privacy rights</Text>
        </View>

        <Text style={styles.sectionTitle}>4. No Guarantee of Accuracy</Text>
        <Text style={styles.body}>
          While we aim to provide helpful summaries and explanations, AI-generated outputs may
          contain errors or inaccuracies.
        </Text>
        <Text style={styles.body}>
          Juno makes{' '}
          <Text style={styles.bold}>
            no guarantees regarding the accuracy, completeness, or reliability
          </Text>{' '}
          of generated summaries or explanations.
        </Text>
        <Text style={styles.body}>
          Users should always confirm medical information with qualified healthcare professionals.
        </Text>

        <Text style={styles.sectionTitle}>5. Temporary Processing</Text>
        <Text style={styles.body}>
          Content submitted to Juno is processed temporarily to generate outputs.
        </Text>
        <Text style={styles.body}>
          Juno is designed{' '}
          <Text style={styles.bold}>
            not to store uploaded recordings, documents, or notes after processing is complete
          </Text>
          .
        </Text>
        <Text style={styles.body}>
          Because of this design, previously submitted information may not be recoverable.
        </Text>

        <Text style={styles.sectionTitle}>6. Service Availability</Text>
        <Text style={styles.body}>
          We may modify, suspend, or discontinue the service at any time without prior notice.
        </Text>
        <Text style={styles.body}>
          The service is provided on an{' '}
          <Text style={styles.bold}>"as-is" and "as-available" basis</Text>.
        </Text>

        <Text style={styles.sectionTitle}>7. Limitation of Liability</Text>
        <Text style={styles.body}>
          To the fullest extent permitted by law, Juno and its operators shall not be liable for
          any damages arising from:
        </Text>
        <View style={styles.bulletList}>
          <Text style={styles.bulletItem}>• Use of the service</Text>
          <Text style={styles.bulletItem}>• Reliance on generated summaries or explanations</Text>
          <Text style={styles.bulletItem}>• Errors or omissions in AI-generated content</Text>
        </View>

        <Text style={styles.sectionTitle}>8. Intellectual Property</Text>
        <Text style={styles.body}>
          All content, branding, and software associated with Juno are the property of Juno or its
          licensors.
        </Text>
        <Text style={styles.body}>
          You may not copy, reproduce, or distribute the service without permission.
        </Text>

        <Text style={styles.sectionTitle}>9. Changes to Terms</Text>
        <Text style={styles.body}>
          We may update these Terms from time to time. Continued use of the service after updates
          constitutes acceptance of the revised terms.
        </Text>

        <Text style={styles.sectionTitle}>10. Contact</Text>
        <Text style={styles.body}>
          Questions about these Terms can be directed to:{' '}
          <Text
            style={styles.link}
            onPress={() => Linking.openURL('mailto:support@meetjuno.health')}
          >
            support@meetjuno.health
          </Text>
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.lightBackground,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 56,
    paddingBottom: 16,
    backgroundColor: Colors.background,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  backButton: {
    padding: 4,
    marginRight: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '600',
    color: Colors.foreground,
    textAlign: 'center',
  },
  headerSpacer: {
    width: 30,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 48,
    gap: 12,
  },
  lastUpdated: {
    fontSize: 13,
    color: Colors.mutedForeground,
    textAlign: 'center',
    marginBottom: 8,
    fontWeight: '500',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.foreground,
    marginTop: 8,
    marginBottom: 2,
  },
  body: {
    fontSize: 15,
    color: Colors.foreground,
    lineHeight: 23,
  },
  bold: {
    fontWeight: '700',
  },
  bulletList: {
    gap: 6,
    paddingLeft: 4,
  },
  bulletItem: {
    fontSize: 15,
    color: Colors.foreground,
    lineHeight: 23,
  },
  link: {
    color: Colors.primary,
    textDecorationLine: 'underline',
  },
});
