import './NewLandingPage.css'
import Header from '../components/shared/Header'
import Footer from '../components/shared/Footer'

function TermsPage() {
  return (
    <div className="min-h-screen w-full" style={{ fontFamily: 'var(--font-family-body)' }}>
      {/* <Header /> */}

      <section
        className="pt-32 pb-16"
        style={{ backgroundColor: 'var(--light-background-color)' }}
      >
        <div className="max-w-3xl mx-auto px-6 sm:px-10 lg:px-16">
          <h1
            className="text-4xl md:text-5xl font-bold mb-2 text-center"
            style={{
              fontFamily: 'var(--font-family-heading)',
              color: 'var(--dark-text-color)',
            }}
          >
            Terms and Conditions
          </h1>
          <p
            className="text-sm text-center mb-12"
            style={{ color: 'var(--gray-text-color)' }}
          >
            <strong>Last Updated: March 2026</strong>
          </p>

          <div
            className="text-base leading-relaxed flex flex-col gap-6"
            style={{ color: 'var(--dark-text-color)' }}
          >
            <p>These Terms and Conditions govern your use of the Juno website and services.</p>
            <p>By using Juno, you agree to these terms.</p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              1. Description of Service
            </h2>
            <p>
              Juno provides an AI-powered tool that helps users summarize and better understand medical
              conversations, recordings, and documents.
            </p>
            <p>The service may:</p>
            <ul className="list-disc pl-6 flex flex-col gap-2">
              <li>Generate summaries of uploaded recordings, notes, or documents</li>
              <li>Explain complex medical information in simpler language</li>
              <li>Suggest potential follow-up questions for healthcare providers</li>
            </ul>
            <p>Juno is designed to support medical understanding and literacy.</p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              2. Not Medical Advice
            </h2>
            <p>
              Juno <strong>does not provide medical advice</strong>.
            </p>
            <p>
              The information generated by Juno is for <strong>informational and educational purposes
              only</strong> and should <strong>not be used as a substitute for professional medical
              advice, diagnosis, or treatment</strong>.
            </p>
            <p>
              Always seek guidance from qualified healthcare professionals regarding medical decisions.
            </p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              3. User Responsibility
            </h2>
            <p>
              You are responsible for the information you upload or submit to the service.
            </p>
            <p>You should only upload content that:</p>
            <ul className="list-disc pl-6 flex flex-col gap-2">
              <li>You have the legal right to use or share</li>
              <li>Does not violate applicable laws or privacy rights</li>
            </ul>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              4. No Guarantee of Accuracy
            </h2>
            <p>
              While we aim to provide helpful summaries and explanations, AI-generated outputs may
              contain errors or inaccuracies.
            </p>
            <p>
              Juno makes <strong>no guarantees regarding the accuracy, completeness, or
              reliability</strong> of generated summaries or explanations.
            </p>
            <p>
              Users should always confirm medical information with qualified healthcare professionals.
            </p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              5. Temporary Processing
            </h2>
            <p>Content submitted to Juno is processed temporarily to generate outputs.</p>
            <p>
              Juno is designed <strong>not to store uploaded recordings, documents, or notes after
              processing is complete</strong>.
            </p>
            <p>
              Because of this design, previously submitted information may not be recoverable.
            </p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              6. Service Availability
            </h2>
            <p>
              We may modify, suspend, or discontinue the service at any time without prior notice.
            </p>
            <p>
              The service is provided on an <strong>"as-is" and "as-available" basis</strong>.
            </p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              7. Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by law, Juno and its operators shall not be liable for
              any damages arising from:
            </p>
            <ul className="list-disc pl-6 flex flex-col gap-2">
              <li>Use of the service</li>
              <li>Reliance on generated summaries or explanations</li>
              <li>Errors or omissions in AI-generated content</li>
            </ul>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              8. Intellectual Property
            </h2>
            <p>
              All content, branding, and software associated with Juno are the property of Juno or its
              licensors.
            </p>
            <p>You may not copy, reproduce, or distribute the service without permission.</p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              9. Changes to Terms
            </h2>
            <p>
              We may update these Terms from time to time. Continued use of the service after updates
              constitutes acceptance of the revised terms.
            </p>

            <h2
              className="text-2xl font-bold mt-4"
              style={{ fontFamily: 'var(--font-family-heading)', color: 'var(--dark-text-color)' }}
            >
              10. Contact
            </h2>
            <p>
              Questions about these Terms can be directed to:{' '}
              <a
                href="mailto:support@meetjuno.health"
                style={{ color: 'var(--primary-color)', textDecoration: 'underline' }}
              >
                support@meetjuno.health
              </a>
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  )
}

export default TermsPage
